language: c
os: linux
branches:
  only:
    - master
    - /^travis.*$/
install:
  - bash .travis/show_versions.sh
  - bash .travis/install.sh
script:
  - bash run_tests.sh
after_failure:
  - cat "${AA_CMAKE_DIR}/CMakeFiles/CMakeOutput.log"
matrix:
  include:
    - os: linux
      env:
        # Python version
        - PY_MAJOR=3
        - PY_MINOR=8
        - PY_PATCH=3
        # Lua version
        - LUA_MAJOR=5
        - LUA_MINOR=3
        - LUA_PATCH=2
        # CMake build directory
        - AA_CMAKE_DIR="${TRAVIS_BUILD_DIR}/build/temp.linux-x86_64-$PY_MAJOR.$PY_MINOR"
        # CMake options
        - AA_LUA_SUPPORT=ON
        - AA_PYTHON_SUPPORT=ON
      before_install:
        - source .travis/setup_python.sh
        - source .travis/setup_lua.sh
    - os: windows
      env: 
        # Python version
        - PY_MAJOR=3
        - PY_MINOR=8
        - PY_PATCH=3
        # CMake build directory
        - AA_CMAKE_DIR="${TRAVIS_BUILD_DIR}/build/temp.win-amd64-$PY_MAJOR.$PY_MINOR/Release"
        # CMake options
        - AA_LUA_SUPPORT=OFF
        - AA_PYTHON_SUPPORT=ON
      before_install:
        - source .travis/setup_python.sh
