language: c
os: linux
branches:
    only:
        - master
        - /^travis.*$/

matrix:
  include:
    - os: linux
      env: GENERATOR="Unix Makefiles"
      before_install:
        - pyenv global 3.6.7
    - os: windows
      before_install:
        - choco install python --version 3.7.6
      env:
        - GENERATOR="Visual Studio 15 2017 Win64"
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
    - cmake --version
    - python --version
    - pip --version
    - pip install --user -r requirements.txt
    - mkdir "${TRAVIS_BUILD_DIR}/build"
    - cd "${TRAVIS_BUILD_DIR}/build"
    - cmake .. -G"${GENERATOR}" -DAA_PYTHON_SUPPORT=OFF
    - cmake --build . --config Debug
    - ctest -V -C Debug
    - cmake .. -G"${GENERATOR}"
    - cmake --build . --config Release
    - ctest -V -C Release
    - cd ..
    - python setup.py
    - python -m pytest -s

after_failure:
  - cat "${TRAVIS_BUILD_DIR}/build/CMakeFiles/CMakeOutput.log"
  - cat "${TRAVIS_BUILD_DIR}/.paths"

