language: c
os: linux
compiler:
        - gcc
        - clang
branches:
        only:
                - master
                - /^travis.*$/
env:
        - PYTHON=3.5.9
        - PYTHON=3.6.11
        - PYTHON=3.7.8
        - PYTHON=3.8.5
before_script:
        - pyenv --version
        - pushd /opt/pyenv/
        - git pull --rebase origin master
        - popd
        - pyenv --version
        - pyenv install $PYTHON
        - pyenv global $PYTHON
        - python --version
        - PYTHON_EXEC=$(pyenv which python)
script:
        - mkdir -p build
        - pushd build
        - cmake --version
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DAA_PYTHON_SUPPORT=ON -DPYTHON_EXECUTABLE=$PYTHON_EXEC
        - cmake --build . --config Release
        - ctest . -C Release
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DAA_PYTHON_SUPPORT=ON -DPYTHON_EXECUTABLE=$PYTHON_EXEC
        - cmake --build . --config Debug
        - ctest . -C Debug
        - popd

