language: c
os: linux
branches:
  only:
    - master
    - /^travis.*$/
install:
  - bash .travis/show_versions.sh
  - sudo $PY_CMD setup.py install
script:
  - bash .travis/run_tests.sh
after_failure:
  - cat "${AA_CMAKE_DIR}/CMakeFiles/CMakeOutput.log"
matrix:
  include:
    - os: linux
      env:
        # Python version
        - PY_MAJOR=3
        - PY_MINOR=8
        - PY_PATCH=3
        # Python executable
        - PY_CMD=python$PY_MAJOR.$PY_MINOR
        # Lua version
        - LUA_MAJOR=5
        - LUA_MINOR=3
        - LUA_PATCH=2
        # Lua executable
        - LUA_CMD=lua
        # CMake environment variables
        - AA_PYTHON_SUPPORT=ON
        - AA_LUA_SUPPORT=ON
        # Path
        - PATH=${TRAVIS_BUILD_DIR}/install/lua:$HOME/.lua:$HOME/.local/bin:$PATH
      before_install:
        - sudo add-apt-repository -y ppa:deadsnakes/ppa
        - sudo apt-get -q update
        - sudo apt-get -y install $PY_CMD $PY_CMD-distutils
        - curl https://bootstrap.pypa.io/get-pip.py | sudo $PY_CMD
        - bash .travis/setup_lua.sh
    - os: windows
      env: 
        # Python version
        - PY_MAJOR=3
        - PY_MINOR=8
        - PY_PATCH=3
        # Python executable
        - PY_CMD=python
        # CMake environment variables
        - AA_PYTHON_SUPPORT=ON
        - AA_LUA_SUPPORT=OFF
        # Path
        - PATH=/c/Python$PY_MAJOR$PY_MINOR:/c/Python$PY_MAJOR$PY_MINOR/Scripts:$PATH
      before_install:
        - choco install python --version $PY_MAJOR.$PY_MINOR.$PY_PATCH 
