language: c
os: linux
branches:
    only:
        - master
        - /^travis.*$/
install:
    - cmake --version
    - python --version
    - pip --version
    - pip install --user -r requirements.txt
script:
    - python setup.py install
    - python -m pytest -s
    - cd ${AA_CMAKE_DIR} && ctest -V -C Release
after_failure:
  - cat "${AA_CMAKE_DIR}/CMakeFiles/CMakeOutput.log"
env:
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
before_install:
  - source .travis/setenv_lua.sh
matrix:
  include:
    - os: linux
      env:
        - AA_CMAKE_DIR="${TRAVIS_BUILD_DIR}/build/temp.linux-x86_64-3.6"
      before_install:
        - pyenv global 3.6.7
    - os: windows
      before_install:
        - choco install python --version 3.7.6
      env: 
        - AA_CMAKE_DIR="${TRAVIS_BUILD_DIR}/build/temp.win-amd64-3.7/Release"
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH