language: c
os: linux
compiler:
        - gcc
        - clang
branches:
        only:
                - master
                - /^travis.*$/
cache:
        - pip
        - directories:
                - $HOME/.pyenv_cache
                - $HOME/.lua
env:
        - PYENV_VERSION='3.5.9'  PYENV_VERSION_STRING='Python 3.5.9'
        - PYENV_VERSION='3.6.11' PYENV_VERSION_STRING='Python 3.6.11'
        - PYENV_VERSION='3.7.8'  PYENV_VERSION_STRING='Python 3.7.8'
        - PYENV_VERSION='3.8.5'  PYENV_VERSION_STRING='Python 3.8.5'
        - LUA_VERSION='5.3.5'
before_install:
        - source config/before_install.sh
before_script:
        - source config/before_script.sh
script:
        - ./config/script.sh
after_failure:
        - ./config/after_failure.sh
