language: c
os: linux
compiler:
        - gcc
        - clang
branches:
        only:
                - master
                - /^travis.*$/
script:
        - mkdir -p build
        - pushd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DAA_PYTHON_SUPPORT=ON
        - cmake --build . --config Release
        - ctest . -C Release
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DAA_PYTHON_SUPPORT=ON
        - cmake --build . --config Debug
        - ctest . -C Debug
        - popd

