language: c
os: linux
python:
    - "3.7"
branches:
  only:
    - master
install:
  - cmake --version
after_failure:
  - cat home/travis/build/guidanoli/aa/build/CMakeFiles/CMakeOutput.log
  - cat home/travis/build/guidanoli/aa/.paths
script-anchors:
  - &script-Makefiles
    - mkdir "${TRAVIS_BUILD_DIR}/build"
    - cd "${TRAVIS_BUILD_DIR}/build"
    - cmake .. -G"${GENERATOR}"
    - cmake --build . --config Release
    - ctest -V -C Release
    - cmake --build . --config Debug
    - ctest -V -C Debug
  - &script-VS15
    - mkdir "${TRAVIS_BUILD_DIR}/build"
    - cd ${TRAVIS_BUILD_DIR}/build
    - cmake .. -G"${GENERATOR}"
    - cmake --build . --config Release
    - ctest -V -C Release
    - cmake .. -G"${GENERATOR}" -DAA_PYTHON_SUPPORT=OFF
    - cmake --build . --config Debug
    - ctest -V -C Debug
    - cd ..
    - python setup.py
    - python -m pytest -s
matrix:
  include:
    - os: linux
      env: GENERATOR="Unix Makefiles"
      script: *script-Makefiles
    - os: windows
      script: *script-VS15
      before_install:
        - choco install python --version 3.7.6
        - python --version
        - pip install --user -r requirements.txt
      env:
        - GENERATOR="Visual Studio 15 2017 Win64"
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH