language: c
os: linux
branches:
    only:
        - master
        - /^travis.*$/
install:
    - source .travis/show_versions.sh
    - python setup.py install
script:
    - source run_tests.sh
after_failure:
  - cat "${AA_CMAKE_DIR}/CMakeFiles/CMakeOutput.log"
matrix:
  include:
    - os: linux
      env:
        - PY_MAJOR=3
        - PY_MINOR=6
        - PY_PATCH=7
        - LUA_MAJOR=5
        - LUA_MINOR=3
        - LUA=lua$LUA_MAJOR$LUA_MINOR
        - AA_CMAKE_DIR="${TRAVIS_BUILD_DIR}/build/temp.linux-x86_64-$PY_MAJOR.$PY_MINOR"
        - AA_LUA_SUPPORT=ON
        - AA_PYTHON_SUPPORT=ON
        - PATH=${TRAVIS_BUILD_DIR}/install/lua:$PATH
      before_install:
        - pyenv global $PY_MAJOR.$PY_MINOR.$PY_PATCH
        - source .travis/setenv_lua.sh
    - os: windows
      env: 
        - PY_MAJOR=3
        - PY_MINOR=7
        - PY_PATCH=6
        - AA_CMAKE_DIR="${TRAVIS_BUILD_DIR}/build/temp.win-amd64-$PY_MAJOR.$PY_MINOR/Release"
        - AA_LUA_SUPPORT=OFF
        - AA_PYTHON_SUPPORT=ON
        - PATH=/c/Python$PY_MAJOR$PY_MINOR:/c/Python$PY_MAJOR$PY_MINOR/Scripts:$PATH
      before_install:
        - choco install python --version $PY_MAJOR.$PY_MINOR.$PY_PATCH
