language: c
os: linux
compiler:
        - gcc
        - clang
branches:
        only:
                - master
                - /^travis.*$/
env:
        - PYTHON_VERSION=python3.5.4
        - PYTHON_VERSION=python3.6.3
        - PYTHON_VERSION=python3.7-dev
before_script:
        - pyenv install $PYTHON_VERSION
        - pyenv global $PYTHON_VERSION
        - PYTHON_EXEC=$(pyenv which python)
        - cmake --version
        - python -V
script:
        - mkdir -p build
        - pushd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DAA_PYTHON_SUPPORT=ON -DPYTHON_EXECUTABLE=$PYTHON_EXEC
        - cmake --build . --config Release
        - ctest . -C Release
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DAA_PYTHON_SUPPORT=ON -DPYTHON_EXECUTABLE=$PYTHON_EXEC
        - cmake --build . --config Debug
        - ctest . -C Debug
        - popd

