language: c
os: linux
compiler:
        - gcc
        - clang
branches:
        only:
                - master
                - /^travis.*$/
cache:
        - pip
        - directories:
                - $HOME/.pyenv_cache
env:
        - PYENV_VERSION='3.5.9'  PYENV_VERSION_STRING='Python 3.5.9'
        - PYENV_VERSION='3.6.11' PYENV_VERSION_STRING='Python 3.6.11'
        - PYENV_VERSION='3.7.8'  PYENV_VERSION_STRING='Python 3.7.8'
        - PYENV_VERSION='3.8.5'  PYENV_VERSION_STRING='Python 3.8.5'
before_install:
        - |
            if [[ -n "$PYENV_VERSION" ]]; then
              wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
              source setup-pyenv.sh
            fi
before_script:
        - python --version
        - pip install --upgrade pip
        - pip install -r config/dev-requirements.txt
        - PYTHON_EXEC=$(pyenv which python)
script:
        - mkdir -p build_release
        - pushd build_release
        - cmake --version
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DAA_PYTHON_SUPPORT=ON -DPYTHON_EXECUTABLE=$PYTHON_EXEC
        - cmake --build . --config Release
        - ctest . -C Release
        - popd
        - export PYTHONPATH=$PWD/lib64
        - $PYTHON_EXEC -m pytest -s --ignore=config/templates
        - mkdir -p build_debug
        - pushd build_debug
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DAA_PYTHON_SUPPORT=ON -DPYTHON_EXECUTABLE=$PYTHON_EXEC
        - cmake --build . --config Debug
        - ctest . -C Debug
        - popd

