language: c
branches:
  only:
    - master
install:
  - cmake --version
script-anchors:
  - &script-Makefiles
    - mkdir ${TRAVIS_BUILD_DIR}/build
    - cmake .. -G"${GENERATOR}"
    - cmake --build . --config Release
    - ctest -C Release
    - cmake --build . --config Debug
    - ctest -C Debug
matrix:
  include:
    - os: linux
      env: GENERATOR="Unix Makefiles"
      script: *script-Makefiles
    - os: osx
      osx_image: xcode7.3
      env: GENERATOR="Unix Makefiles"
      script: *script-Makefiles