language: c
os: linux
branches:
    only:
        - master
        - /^travis.*$/
install:
    - cmake --version
    - python --version
    - pip --version
    - pip install --user -r requirements.txt
    - python setup.py install
    - python -m pytest -s
    - cd build/temp*/Release && ctest -V -C Release
after_failure:
  - cat "${TRAVIS_BUILD_DIR}/build/temp*/Release/CMakeFiles/CMakeOutput.log"
matrix:
  include:
    - os: linux
      env:
        - AA_BUILD_TESTS=ON
      before_install:
        - pyenv global 3.6.7
    - os: windows
      before_install:
        - choco install python --version 3.7.6
      env: 
        - AA_BUILD_TESTS=ON
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH